jobs:
  include:
    - language: objective-c
      osx_image: xcode13.1
      sudo: false
      install: skip
      script:
        - xcodebuild -version
        - xcrun instruments -s devices
        - echo staring build and test...
        - xcrun simctl list devices
        - xcrun simctl list --json
    - language: ruby
      rvm: 2.7.5
      install: skip
      script: ruby -v
